stages:
  - deploy

snap:
  stage: deploy
  image: "cibuilds/snapcraft:core20"
  script:
    - snapcraft
    - echo $SNAPCRAFT_LOGIN_DATA | base64 --decode --ignore-garbage > snapcraft.login
    - snapcraft login --with snapcraft.login
    - snapcraft upload --release=edge veloren*.snap
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: never
