name: veloren
base: core20
summary: A novel multiplayer voxel RPG
description: |
  Veloren is a multiplayer voxel RPG written in Rust.
  Veloren takes inspiration from games such as Cube World, Minecraft and Dwarf Fortress.
  The game is currently under heavy development, but is playable.
confinement: strict
adopt-info: veloren

architectures:
  - build-on: amd64

apps:
  veloren:
    adapter: full
    command: bin/veloren-voxygen
    command-chain:
      - "snap/command-chain/alsa-launch"
      - "bin/desktop-launch"
      - "bin/launcher"
    desktop: usr/share/applications/veloren.desktop
    plugs:
      - opengl
      - wayland
      - x11
      - desktop
      - desktop-legacy # needed for ibus support
      - audio-playback
      - joystick
      - network
      - network-bind
      - alsa
  server:
    command: bin/veloren-server-cli
    command-chain:
      - "bin/launcher"
    plugs:
      - network
      - network-bind

# Needed for routing ALSA through Pulseaudio
# https://snapcraft-alsa.readthedocs.io/en/latest/index.html
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    symlink: $SNAP/usr/share/alsa
  /usr/share/vulkan:
    symlink: $SNAP/usr/share/vulkan
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so
parts:
  launcher:
    plugin: dump
    source: snap/local/launcher
    organize:
      launcher.sh: bin/launcher
    stage:
      - bin/launcher
  icon-file:
    plugin: dump
    source: https://gitlab.com/veloren/veloren.git
    organize:
      assets/voxygen/net.veloren.veloren.png: usr/share/icons/veloren.png
    stage:
      - usr/share/icons/veloren.png
  desktop-file:
    plugin: dump
    source: https://gitlab.com/veloren/veloren.git
    override-pull: |
      snapcraftctl pull
      # Patch icon path and executable name in desktop file
      sed -i.new 's|Exec=.*|Exec=veloren|g;s|Icon=.*|Icon=${SNAP}/usr/share/icons/veloren.png|g' \
        assets/voxygen/net.veloren.veloren.desktop
    organize:
      assets/voxygen/net.veloren.veloren.desktop: usr/share/applications/veloren.desktop
    stage:
      - usr/share/applications/veloren.desktop
  veloren:
    plugin: rust
    source: https://gitlab.com/veloren/veloren.git
    rust-path: [voxygen]
    build-packages:
      - git-lfs
      - libglib2.0-dev
      - libcairo2-dev
      - libasound2-dev
      - libpango1.0-dev
      - libatk1.0-dev
      - libgdk-pixbuf2.0-dev
      - libgtk-3-dev
      - libudev-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      # needed for shaderc:
      - cmake
      - ninja-build
      - python3
      - python-is-python3
    override-pull: |
      snapcraftctl pull
      git-lfs install
      git config lfs.url "https://gitlab.com/veloren/veloren.git/info/lfs"
      git-lfs fetch
      git-lfs checkout
      version="$(git describe --always | sed -e 's/-/+git/;y/-/./')"
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "devel"
    build-environment:
      - VELOREN_USERDATA_STRATEGY: system
    override-build: |
      if ! command -v rustup 2>/dev/null; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile=minimal
        export PATH="${HOME}/.cargo/bin:${PATH}"
      fi
      rustup override set $(cat rust-toolchain)
      # Cannot install virtual manifest packages directly due to https://github.com/rust-lang/cargo/issues/4101
      cargo build --release --bin veloren-voxygen --bin veloren-server-cli
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp target/release/veloren-voxygen $SNAPCRAFT_PART_INSTALL/bin
      cp target/release/veloren-server-cli $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/veloren
      cp -r assets $SNAPCRAFT_PART_INSTALL/usr/share/veloren
  # Shared libraries required by veloren at runtime
  veloren-runtime:
    plugin: nil
    stage-packages:
    - libasound2
    - libatk-bridge2.0-0
    - libatk1.0-0
    - libatspi2.0-0
    - libcairo-gobject2
    - libcairo2
    - libdatrie1
    - libepoxy0
    - libfontconfig1
    - libfreetype6
    - libgdk-pixbuf2.0-0
    - libgraphite2-3
    - libgtk-3-0
    - libharfbuzz0b
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpixman-1-0
    - libpng16-16
    - libthai0
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1
    - libxcb-render0
    - libxcb-shm0
    - libxcb-shape0
    - libxcb-xfixes0
    - libxcomposite1
    - libxdamage1
    - libxext6
    - libxi6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libx11-xcb1
    - libgl1-mesa-glx
    - libx11-6
    - libxcursor1
    - libudev1
    - libibus-1.0-5 # needed for ibus support
    - libegl1-mesa # bundle libEGL
    - libxkbcommon-x11-0
    - libvulkan1
    - mesa-vulkan-drivers
  # Needed for routing ALSA through Pulseaudio
  # https://snapcraft-alsa.readthedocs.io/en/latest/index.html
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-commit: c08d5df21761b56679088b06411694b00fff9475
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
  # Basic desktop application support. Among other things,
  # this is required in order for Veloren to use ibus
  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
